Table ACCOUNTS {
  ACCOUNT_ID nvarchar [pk, not null]
  ACCOUNT_NM varchar(150)
  ACCOUNT_DS varchar(250)
  ACTIVE varchar(1)
  CREATE_USER_ID varchar(50)
  CREATE_TS nvarchar
  UPDATE_USER_ID varchar(50)
  UPDATE_TS nvarchar
  ACCT_ROLE_ID varchar(3)
  ACCT_SALES_ID nvarchar
  PROG_MNGR_ID nvarchar
  CUSTOMER_CONTACT varchar(200)
  SHIP_TO_ADDRESS varchar(200)
  CUSTOMER_ADDRESS varchar(200)
  ORACLE_ID varchar(20)
  IS_PROSPECT varchar(5)
  SERVICENOW_ID varchar(20)
  MASTER_CUSTOMER_SYSID varchar(100)
}

Table APPROVAL_ESCALATIONS_LU {
  APPROVAL_ESC_ID int [not null]
  APPROVAL_LU_ID int
  APPROVAL_ROLE_ID int
  THRESHOLD decimal(18,2)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  USER_ID decimal(38,10)
}

Table APPROVAL_LEVEL_LU {
  APPROVAL_LEVEL_ID int [not null]
  LEVEL_DS varchar(50)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table APPROVALS {
  APPROVAL_ID int [pk, not null]
  TASK_ID int
  APPROVAL_LU_ID int
  APPROVAL_MESSAGE varchar(4000)
  APPROVAL_USER_ID int
  APPROVAL_LEVEL_ID int
  RESPONSE_ID int
  APPROVER_COMMENTS varchar(4000)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  QUOTE_ID decimal(38,10)
  FR_ID decimal(38,10)
}

Table APPROVALS_LU {
  APPROVAL_LU_ID int [not null]
  APPROVAL_TYPE_ID int
  APPROVAL_DS varchar(250)
  PROJECT_DATA_ID int
  TOOL_ID int
  APPROVAL_SCREEN_ID int [not null]
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table CASE_DATA {
  CASE_DATA_ID int [pk, not null]
  CASE_ID int [not null]
  VERSION_ID int
  REFERENCE_NM varchar(250)
  CONTENT_TX varchar(4000)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table CASES {
  CASE_ID int [not null]
  TASK_ID int
  TOOL_VERSION_ID int
  DATA_ITEM1 varchar(4000)
  DATA_ITEM2 varchar(4000)
  DATA_ITEM3 varchar(4000)
  CREATE_USER_ID varchar(50)
  CASE_STATUS varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  ACCOUNT_ID int
  DATA_ITEM4 varchar(4000)
  SHARED_SOLUTION_DATA_ID decimal(38,10)
  SUB_PROJECT_TYPE varchar(20)
}

Table CELL_REFERENCE {
  REFERENCE_NM varchar(100) [not null]
  VERSION_ID int [not null]
  CELL_TYPE_CD varchar(10)
  PROCESS_SQN int
  ORDER_SQN int
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table CELL_TYPE {
  REFERENCE_NM varchar(100) [not null]
  VERSION_ID int [not null]
  CELL_TYPE_CD varchar(10)
  PROCESS_SQN int
  ORDER_SQN int
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table Clients {
  id uuid [not null]
  name nvarchar(510)
  client_id nvarchar(510) [pk]
  client_secret_hash nvarchar(1024)
  created_at datetime
}

Table COMMUNICATION_PLAN {
  COMMUNICATION_ID decimal(38,10) [not null]
  SOW_CASE_ID decimal(38,10) [not null]
  COMMUNICATION_DESCRIPTION varchar(150)
  MEDIUM_HOW varchar(100)
  ATTENDES varchar(100)
  FREQUENCY varchar(100)
  CREATE_TS datetime2
  CREATE_USER_ID int
  UPDATE_USER_ID int
  UPDATE_TS datetime2
}

Table COPY_PRICER_MODEL {
  ID_COPY_PRICER_MODEL int [not null]
  QUOTE_NAME_REVISION varchar(20) [not null]
  QUOTE_ID int [not null]
  CASE_ID int [not null]
  TASK_ID int [not null]
  USER_ID int [not null]
}

Table CUSTOMER_ADD_UPDATED {
  ID_ADDRESS nvarchar(76)
  ADDRESS_LINE1 nvarchar(120)
  ADDRESS_LINE2 nvarchar(120)
  CITY nvarchar(120)
  STATE_PROVINCE_REGION nvarchar(120)
  ZIP_POSTAL_CODE nvarchar(120)
  ACCOUNT_ID nvarchar(76)
}

Table CUSTOMER_ADDRESS {
  ID_ADDRESS decimal(38,10)
  ADDRESS_LINE1 varchar(60)
  ADDRESS_LINE2 varchar(60)
  CITY varchar(60)
  STATE_PROVINCE_REGION varchar(60)
  ZIP_POSTAL_CODE varchar(60)
  ACCOUNT_ID decimal(38,10)
}

Table CUSTOMER_CATEGORY {
  CUSTOMER_CATEGORY_ID decimal(38,10) [pk, not null]
  CUSTOMER_CATEGORY_NM varchar(15) [not null]
  CUSTOMER_CATEGORY_DESCRIPTION varchar(50)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table DataRecords {
  id uuid [pk, not null]
  name nvarchar(510)
  value nvarchar(510)
  created_at datetime
}

Table DESIGN_CAPACITY_RESERVED {
  CAPACITY_RESERVED_ID decimal(38,10) [not null]
  CAPACITY_RESERVED_NM varchar(15) [not null]
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table DESIGN_COMPLEX_CELL_REFERENCE {
  REFERENCE_NM varchar(100) [not null]
  VERSION_ID decimal(38,10) [not null]
  CELL_TYPE_CD varchar(20)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
}

Table DESIGN_COMPLEX_CHANGE_LOGS {
  CHLOG_ID decimal(38,10) [not null]
  DESIGN_ID decimal(38,10)
  CREATE_USER_ID varchar(20)
  CREATE_DT nvarchar
  UPDATE_DT nvarchar
  OPP_ID decimal(38,10)
}

Table DESIGN_COMPLEX_CHLOG_ENTRIES {
  CHLOG_ENTRY_ID decimal(38,10) [not null]
  CHLOG_ID decimal(38,10)
  CREATE_DT datetime2
  TYPE varchar(50)
  REASON varchar(100)
  ADC_ENG_HRS float
  TECHNICIAN_HRS float
  SCHEDULE_DAYS float
  COST float
  NOTES varchar(100)
  DESIGN_ID decimal(38,10)
  DESCRIPTION varchar(100)
  CREATE_USER_ID varchar(20)
}

Table DESIGN_COMPLEX_SUM_CELL_REF {
  REFERENCE_NM varchar(100) [not null]
  VERSION_ID decimal(38,10) [not null]
  CELL_TYPE_CD varchar(20)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
}

Table DESIGN_COMPLEXITY {
  DESIGN_ID int [not null]
  TASK_ID int
  TOOL_VERSION_ID int
  TOOL_DESCRIPTION varchar(4000)
  DESIGN_STATUS varchar(50)
  DESIGN_COMPLEXITY_LEVEL int
  PL_HOURS int
  ADC_ENG int
  UPDATED_DS nvarchar
  COMMENTS varchar(4000)
  OPP_ID int
  ADC_TECH int
}

Table DESIGN_COMPLEXITY_DATA {
  DESIGN_DATA_ID int [not null]
  DESIGN_ID int [not null]
  VERSION_ID int [not null]
  REFERENCE_NM varchar(250)
  CONTENT_TX varchar(4000)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  DESIGN_STATUS varchar(20)
  DESIGN_TYPE varchar(20)
}

Table "DIS.OPP_MG_NPI_REPEAT" {
  REFERENCE_NM varchar(100) [not null]
  VERSION_ID int [not null]
  CELL_TYPE_CD varchar(10)
  PROCESS_SQN int
  ORDER_SQN int
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table DIS_MASTER_TABLE {
  DIS_MASTER_KEY varchar(20) [not null]
  ID nvarchar [pk]
  ACCOUNT_ID nvarchar
  CUSTOMER varchar(150)
  CUSTOMER_BUYER_ID nvarchar
  REGION_ID nvarchar
  SALES_ACCOUNT_OWNER varchar(120)
  CREATE_USER_ID varchar(50)
  CREATE_TS nvarchar
  UPDATE_USER_ID varchar(50)
  UPDATE_TIMESTAMP nvarchar
}

Table DIS_SHARED_SOLUTION_DATA {
  SOLUTION_ID decimal(38,10) [not null]
  TER_PN varchar(50)
  PLATFORM varchar(50)
  ACTUAL_DESIGN_CMPLX_LEVEL decimal(38,10)
  ACTUAL_FAB_CMPLX_LEVEL decimal(38,10)
  PLANNED_DESIGN_CMPLX_LEVEL decimal(38,10)
  PLANNED_FAB_CMPLX_LEVEL decimal(38,10)
  PROJECT_LEAD_ID decimal(38,10)
  CHDC_ACCOUNT_LEAD_ID decimal(38,10)
  CHDC_MANAGER_ID decimal(38,10)
  CHDC_DESIGNER_ID decimal(38,10)
  OPERATIONS_OWNER_ID decimal(38,10)
  REGIONAL_MANAGER_ID decimal(38,10)
  PLANNER_ID decimal(38,10)
  SUPPLIER_QUALITY_ENGINEER decimal(38,10)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TIMESTAMP nvarchar
  CHDC_CROSS_CHECKER decimal(38,10)
  CHDC_ENGINEER_ID decimal(38,10)
  PCB_TER_PN varchar(50)
  MLO_TER_PN varchar(50)
  PROJECT_MANAGER_ID decimal(38,10)
}

Table ERROR {
  ERROR_ID int [pk, not null]
  USER_NM varchar(50)
  QUOTE_ID varchar(50)
  PARAMETER varchar(50)
  DIAG varchar(50)
  CREATE_TS datetime2
}

Table FILES {
  FILE_ID int [not null]
  FILE_LU_ID int [not null]
  FILE_VER_NO int [not null]
  FILE_NM varchar(250)
  FILE_COMMENTS varchar(4000)
  PATH varchar(500)
  PROJECT_ID int
  SUBPROJ_ID int
  TASK_ID int
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table FILES_LU {
  FILE_LU_ID int [not null]
  FILE_DS varchar(150) [not null]
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table FINAL_REVIEW {
  FR_ID decimal(38,10) [not null]
  STATUS varchar(20)
  NOTES varchar(100)
  CHDC_ACCOUNT_LEAD_ID decimal(38,10)
  PROJECT_LEAD_ID decimal(38,10)
  CHDC_CROSS_CHECKER_ID decimal(38,10)
  PLANNER_ID decimal(38,10)
  CREATE_TS datetime2
  CREATE_USER_ID varchar(20)
  UPDATE_USER_ID varchar(20)
  UPDATE_TS datetime2
  HLA_ID decimal(38,10) [not null]
  CHDC_MANAGER decimal(38,10)
  CHDC_DESIGN_LEAD decimal(38,10)
}

Table FINAL_REVIEW_FILES {
  FR_FILE_ID decimal(38,10) [not null]
  FILE_ID decimal(38,10) [not null]
  OPEN_TO_CUSTOMER decimal(38,10)
  OPEN_TO_PLANNER decimal(38,10)
  CREATE_TS datetime2
  CREATE_USER_ID varchar(20)
  UPDATE_TS datetime2
  UPDATE_USER_ID varchar(20)
  FR_ID decimal(38,10) [not null]
}

Table GENERAL_CATALOG {
  CATALOG_ID int [not null]
  NAME varchar(20)
  DESCRIPTION varchar(45)
  TYPE varchar(20) [not null]
}

Table HLA {
  HLA_ID decimal(38,10) [pk, not null]
  PROJECT_ID decimal(38,10) [not null]
  CREATE_TS datetime2
  CREATE_USER_ID varchar(20)
  UPDATE_USER_ID varchar(20)
  UPDATE_TS datetime2
  SOW_ID decimal(38,10) [not null]
  DIS_MASTER_KEY varchar(20)
  SHARED_SOLUTION_DATA_ID decimal(38,10)
}

Table IMPORT_TYPE {
  ID decimal(38,10) [pk]
  NAME varchar(60)
  DESCRIPTION varchar(60)
}

Table INCOTERMS {
  ID decimal(38,10) [pk]
  NAME varchar(20)
  DESCRIPTION varchar(60)
}

Table ISSUE_COMMENTS {
  ISSUE_COMM_ID int [not null]
  ISSUE_ID int
  FILE_ID int
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  ISSUE_COMMENT varchar(4000)
  SPEND_EFFORT decimal(8,1)
}

Table ISSUES {
  ISSUE_ID int [not null]
  ISSUE_DS varchar(4000)
  PLANNED_IMP varchar(4000)
  PROJECT_ID int
  SUBPROJ_ID int
  TASK_ID int
  ISSUE_FROM varchar(50)
  ISSUE_TO varchar(50)
  STATUS varchar(50)
  SPEND_EFFORT decimal(8,1)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table LOG {
  LOG_ID decimal(38,10) [pk, not null]
  TOOL_ID decimal(38,10) [not null]
  ACTION varchar(100) [not null]
  CREATE_TS datetime2
  CREATE_USER_ID varchar(20)
  UPDATE_USER_ID varchar(20)
  UPDATE_TS datetime2
  LOG_DETAILS varchar(100)
  SOW_ID decimal(38,10)
  SOW_CASE_ID decimal(38,10)
  FR_ID decimal(38,10)
}

Table MLO_DESIGN_CUSTOMER_LEVEL_INTERACTION {
  CUSTOMER_LEVEL_INTERACTION_NO decimal(38,10) [not null]
  CUSTOMER_NAME varchar(50) [not null]
  ACTIVE char(1)
  CREATE_USER_ID varchar(20)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(20)
  UPDATE_TS datetime2
}

Table OPP_MG_CUSTOMER_INDUSTRIES_SUB_SEGMENT {
  SUB_SEGMENT_ID nvarchar
  SUB_SEGMENT_NM varchar(45)
  CREATE_USER_ID nvarchar(90)
  CREATE_TS datetime2
  UPDATE_USER_ID datetime2
  UPDATE_TS datetime2
  SEGMENT_ID nvarchar [not null]
}

Table OPP_MG_CUSTOMER_OPPORTUNITIES {
  OPPORTUNITY_ID nvarchar [not null]
  CUSTOMER_PROJECT_ID nvarchar [not null]
  TER_OPP_ID varchar(20) [not null]
  TER_PART_NUMBER varchar(50)
  TER_DESING_IN_REGION_ID nvarchar [not null]
  FUNDING_TYPE varchar(100) [not null]
  TEST_PLATFOTM varchar(20) [not null]
  TEST_TYPE varchar(20) [not null]
  HW_TYPE_ID nvarchar [not null]
  AWP_SEED_FILE_ID varchar(20)
  TESTER_CONFIGURATION_INFO varchar(20)
  PLANNED_DESIGN_CMPLX_LEVEL nvarchar
  PLANNED_FAB_CMPLX_LEVEL nvarchar
  ACTUAL_DESIGN_CMPLX_LEVEL nvarchar
  ACTUAL_FAB_CMPLX_LEVEL nvarchar
  OPP_STATUS varchar(15) [not null]
  TECHNICAL_CLOSURE varchar(15)
  COMMERCIAL_CLOSURE varchar(15)
  COMPETITIVE_CLOSURE varchar(15)
  WON_LOSS_REASON varchar(50)
  PROJECT_AWARD_BASELINE_DATE datetime2 [not null]
  PROJECT_AWARD_PROJECTED_DATE datetime2
  PROJECT_AWARD_ACTUAL_DATE datetime2
  DESING_START_BASELINE_DATE datetime2
  DESING_START_PROJECTED_DATE datetime2
  DESING_START_ACTUAL_DATE datetime2
  PROJECT_LEAD_NOTE varchar(4000)
  CREATE_USER_ID varchar(50)
  CREATE_TS nvarchar
  UPDATE_USER_ID varchar(50)
  UPDATE_TS nvarchar
  CUSTOMER_PURCHASING_CONTACT varchar(50)
  CUSTOMER_TECHNICAL_CONTACT varchar(50)
  TER_SALES_ACCOUNT_OWNER varchar(50)
  DIS_PROJECT_LEAD_ID nvarchar [not null]
  DIS_DESIGN_LEAD_ID nvarchar
  DIS_OPERATIONS_OWNER_ID nvarchar
  DIS_REGIONAL_MANAGER_ID nvarchar [not null]
  DIS_APPS_SUPPORT_NAME varchar(50)
  DIS_APPS_SUPPORT_EMAIL varchar(50)
  DIS_APPS_SUPPORT_LOCATION_ID nvarchar
  KEY_SOCKET varchar(3)
  DIS_MASTER_KEY varchar(20)
  SHARED_SOLUTION_DATA_ID nvarchar
  DIS_OPP_DESCRIPTION varchar(300)
  DESING_GERBER_OUT_DATE datetime2
  PROJECT_CUSTOMER_NEED_DATE datetime2
  LOCAL_DESIGN nvarchar
  MECH_DESIGN nvarchar
  SIMULATION nvarchar
  DESIGN_PLANNER_NOTES varchar(300)
  DESIGN_CAPACITY_RESERVED nvarchar
  PRIORITY_LEVEL nvarchar
  DESING_APPROVAL_ACTUAL_DATE datetime2
  DESING_MLO_GERBER_OUT_DATE datetime2
  DIS_PROJECT_MANAGER nvarchar
  PCB_TER_PN varchar(50)
  MLO_TER_PN varchar(50)
  SHARED_ID varchar(20)
  ASSY_FINISH_DATE datetime2
  DIB_DIAG_DATE datetime2
  ACTIVE nvarchar [not null]
  DIS_REPEAT_COORDINATOR_ID nvarchar
  DIS_TECHNICAL_SALES nvarchar
  ACTUAL_GERBER_OUT_DATE datetime2
  ACTUAL_MLO_GERBER_OUT_DATE datetime2
  DIS_DESIGN_MANAGER nvarchar
}

Table OPP_MG_CUSTOMER_PROJECTS {
  CUSTOMER_ID nvarchar [not null]
  SPECIFIER_REGION_ID nvarchar
  SPECIFIER_CODE varchar(20)
  SHIP_TO_CUSTOMER_ID varchar(20)
  SHIP_TO_CUSTOMER_REGION_ID nvarchar
  SHIP_TO_CUSTOMER_CODE varchar(20)
  CUSTOMER_DEVICE_NAME varchar(500) [not null]
  DEVICE_PART_NUMBER varchar(500)
  INDUSTRY_ID nvarchar [not null]
  SEGMENT_ID nvarchar [not null]
  SUBSEGMENT_ID nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS nvarchar
  UPDATE_USER_ID varchar(50)
  UPDATE_TS nvarchar
  CUSTOMER_PURCHASING_CONTACT varchar(50)
  CUSTOMER_TECHNICAL_CONTACT varchar(50)
  TER_SALES_ACCOUNT_OWNER varchar(50)
  OPP_MG_STAGE varchar(45)
  ACCOUNT_ID nvarchar [not null]
  DIS_MASTER_KEY varchar(20)
  CUSTOMER_CATEGORY_ID nvarchar
  ACTIVE nvarchar [not null]
  IS_STANDARDPRODUCT nvarchar [not null]
  APIRES_STATUS varchar(20)
  APIRES_RESPONSE nvarchar
  API_PAYLOAD nvarchar
  IS_NEXPROBE nvarchar [not null]
}

Table OPP_MG_INDUSTRIES {
  INDUSTRY_ID int
  INDUSTRY_NM varchar(100) [not null]
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table OPP_MG_INDUSTRIES_SEGMENT {
  SEGMENT_ID nvarchar [not null]
  SEGMENT_NAME varchar(50) [not null]
  INDUSTRY_ID nvarchar [not null]
  CREATE_USER_ID varchar(50)
  CREATE_TS nvarchar
  UPDATE_USER_ID varchar(50)
  UPDATE_TS nvarchar
}

Table OPP_MG_NPI_REPEAT {
  NPI_REPEAT_ID nvarchar [not null]
  PROJECTED_DATE datetime2
  VOLUME_FORECAST nvarchar
  REPEAT_NUMBER nvarchar
  OPPORTUNITY_ID nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS nvarchar
  UPDATE_USER_ID varchar(50)
  UPDATE_TS nvarchar
  BASELINE_COMMIT_DATE datetime2
  ACTUAL_DATE datetime2
  LIKELIHOOD_AWARD_CONFIDENCE nvarchar
  PROJECT_TYPE_ID nvarchar [not null]
  EXPECTED_SELLING_PRICE nvarchar
  EXPECTED_COGS nvarchar
  EXPECTED_STANDARD_MARGIN nvarchar
  QUOTE_ID nvarchar
  SUPPLY_CHAIN_ID nvarchar
  APL_USAGE_BASELINE_TARGET nvarchar
  APL_USAGE_ACTUAL_RESULT nvarchar
  DIB_DIAG_COVER_BASELINE_TARGET varchar(20)
  DIB_DIAG_COVER_ACTUAL_RESULT varchar(20)
  VISION_SYS_USE_BASELINE_TARGET varchar(3)
  VISION_SYS_USE_ACTUAL_RESULT varchar(3)
  AUTO_PROBE_RF_USE_BASELINE_TGT varchar(3)
  AUTO_PROBE_RF_USE_ACTUAL_RES varchar(3)
  BIN1_SER_LOC_BASELINE_TGT_ID nvarchar
  BIN1_SER_LOC_ACTUAL_RES_ID nvarchar
  TOTAL_REVENUE nvarchar
  DIS_MASTER_KEY varchar(20)
  SHARED_SOLUTION_DATA_ID nvarchar
  REPEAT_STATUS varchar(15)
  REPEAT_CUSTOMER_NEED_DATE datetime2
  SITE_COUNT_QTY nvarchar
  MLO_SOLUTION varchar(3)
  ASSY_FINISH_REPEAT datetime2
  NRE_NPI nvarchar
  SO_NUMBER nvarchar
  CUSTOMER_COMMIT_SHIP_DATE datetime2
  CUSTOMER_COMMIT_SHIP_DATE_CHANGE_NOTE varchar(4000)
  CUSTOMER_HW_ACCEPTANCE_DATE datetime2
  SERVICENOW_OPPORTUNITY_ID varchar(100)
  APIRES_STATUS varchar(20)
  APIRES_RESPONSE nvarchar
  API_PAYLOAD nvarchar
  IS_SPLIT_SHIPMENT nvarchar
}

Table OPP_MG_NPI_REPEAT_DATE_CHANGE_APPROVALS {
  DATE_CHANGE_APPROVALS_ID decimal(38) [not null]
  NPI_REPEAT_ID decimal(38) [not null]
  APPROVALS_ID decimal(38) [not null]
  NEW_DATE datetime2
  CREATE_TS datetime2
  CREATE_USER_ID varchar(20)
  UPDATE_USER_ID varchar(20)
  UPDATE_TS datetime2
}

Table PAYMENT_TYPE {
  ID decimal(38) [pk]
  NAME varchar(60)
  DESCRIPTION varchar(60)
  SEQUENCE decimal(38)
}

Table PROJECT_DATA {
  DATA_ID nvarchar [not null]
  PROJECT_DATA_ID nvarchar [pk]
  DATA_VALUE varchar(4000)
  SUBPROJ_ID nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table PROJECT_DATA_REFERENCE {
  PROJECT_DATA_ID nvarchar [not null]
  DATA_ITEM_DS varchar(250)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table PROJECT_SIZING_TOFU {
  PROJECT_SIZING_ID varchar(2000) [not null]
  REFERENCE_NM varchar(200)
  CONTENT_TX varchar(200)
  CREATE_DATE nvarchar
  CREATE_USER varchar(200)
  UPDATE_DATE nvarchar
  UPDATE_USER varchar(200)
  QUOTE_ID nvarchar
  CONSECUTIVE nvarchar [not null]
  FLAG_TOFU varchar(2)
}

Table PROJECT_TYPE {
  PROJECT_TYPE_ID nvarchar [pk]
  PROJECT_TYPE_NM varchar(25)
  PROJECT_TYPE_DS varchar(250)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_IS varchar(50)
  UPDATE_TS datetime2
  TOOL_ID nvarchar
}

Table PROJECTS {
  PROJECT_ID nvarchar [pk, not null]
  PROJECT_NM varchar(250)
  PROJECT_TYPE_ID nvarchar
  STAGE_ID nvarchar
  TER_PN varchar(50)
  PROJECT_LEAD_ID nvarchar
  DESIGN_LEAD_ID nvarchar
  REGION_ID nvarchar
  CUSTOMER varchar(150)
  CUSTOMER_BUYER_ID nvarchar
  CUSTOMER_SPECIFIER_ID nvarchar
  PLANNER_ID nvarchar
  SQE_ID nvarchar
  PROJECT_AWARD_DT datetime2
  KICKOFF_DT datetime2
  DELIVERY_DT datetime2
  PLATFORM_DS varchar(50)
  APPLICATION_DS varchar(50)
  CREATE_USER_ID varchar(50)
  CREATE_TS nvarchar
  UPDATE_USER_ID varchar(50)
  UPDATE_TS nvarchar
  ACCOUNT_ID nvarchar
  QUOTES_ID nvarchar
  PR_QUANTITY nvarchar
  TER_PROJECT_ID varchar(50)
  PCB_BUDGET nvarchar
  PCB_PRICE nvarchar
  BOM_BUDGET nvarchar
  BOM_ACTUAL nvarchar
  ASSY_TEST_BUDGET nvarchar
  ASSY_TEST_ACTUAL nvarchar
  MLO_BUDGET nvarchar
  MLO_ACTUAL nvarchar
  MLO_ATTACH_BUDGET nvarchar
  MLO_ATTACH_ACTUAL nvarchar
  TER_STD_PARTS_BUDGET nvarchar
  TER_STD_PARTS_ACTUAL nvarchar
  TOTAL_COST nvarchar
  UNIT_COST nvarchar
  DIS_MASTER_KEY varchar(20)
  SHARED_SOLUTION_DATA_ID nvarchar
  OPP_NPI_REPEAT_ID nvarchar
  SHARED_ID varchar(50)
}

Table QUARTERS {
  Q_STRING varchar(3) [not null]
  START_MONTH nvarchar
  END_MONTH nvarchar
}

Table QUOTE_STATUS {
  STATUS_ID nvarchar [not null]
  SEQ_NO nvarchar
  STATUS_DS varchar(50) [not null]
  APPROVAL_ID nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table QUOTES {
  QUOTE_ID nvarchar
  QUOTE_NUMBER nvarchar
  DESCRIPTION nvarchar
  ACCOUNT_ID nvarchar
  SOLUTION_TYPE_ID nvarchar
  REVISION nvarchar
  DATE_OF_INQUIRY nvarchar
  IMPORT_TYPE nvarchar
  PAYMENTS_TYPES nvarchar
  CREATE_USER_ID nvarchar
  CREATE_TS datetime2
  UPDATE_USER_ID nvarchar
  UPDATE_TS datetime2
  CUSTOMER_NEED_DATE nvarchar
  ESTIMATED_LEAD_TIME nvarchar
  QUOTES_STATUS nvarchar
  QUOTE_TEMPLATE nvarchar
  CUSTOMER_ADDRESS nvarchar
  REGION_ID nvarchar
  CUSTOMER_CONTACT nvarchar
  SHIP_TO nvarchar
  CUSTOMER_RFQ nvarchar
  QUOTE_PART_NUMBER nvarchar
  INCOTERMS_ID nvarchar
  TERADYNE_ADDRESS nvarchar
  TERADYNE_ENTITY_CONTACT nvarchar
  SALES_PERSON nvarchar
  DIS_MASTER_KEY nvarchar
  SHARED_SOLUTION_DATA_ID nvarchar
}

Table QUOTES_CASE_DATA {
  CASE_DATA_ID nvarchar
  CASE_ID nvarchar
  VERSION_ID nvarchar
  REFERENCE_NM varchar(250)
  CONTENT_TX varchar(4000)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table QUOTES_CASES {
  CASE_ID nvarchar
  TASK_ID nvarchar
  TOOL_VERSION_ID nvarchar
  DATA_ITEM1 nvarchar
  DATA_ITEM2 nvarchar
  DATA_ITEM3 nvarchar
  CREATE_USER_ID nvarchar
  CASE_STATUS nvarchar
  CREATE_TS datetime2
  UPDATE_USER_ID nvarchar
  UPDATE_TS datetime2
  ACCOUNT_ID nvarchar
  QUOTE_ID nvarchar
  REVISION_CONSECUTIVE nvarchar
  QUOTE_NUMBER nvarchar
  TOFU_PL_SUGGESTED_PCB_DISCOUNT nvarchar
  TOFU_PL_SUGGESTED_NRE_DISCOUNT nvarchar
}

Table QUOTES_CASES_UPDATED {
  CASE_ID numeric(10)
  TASK_ID numeric(10)
  TOOL_VERSION_ID numeric(10)
  DATA_ITEM1 nvarchar(8000)
  DATA_ITEM2 nvarchar(8000)
  DATA_ITEM3 nvarchar(8000)
  CREATE_USER_ID nvarchar(100)
  CASE_STATUS nvarchar(100)
  CREATE_TS datetime2
  UPDATE_USER_ID nvarchar(100)
  UPDATE_TS datetime2
  ACCOUNT_ID numeric(10)
  QUOTE_ID nvarchar(76)
  REVISION_CONSECUTIVE numeric(10)
  QUOTE_NUMBER nvarchar(240)
  TOFU_PL_SUGGESTED_PCB_DISCOUNT float
  TOFU_PL_SUGGESTED_NRE_DISCOUNT float
}

Table QUOTES_CELL_REFERENCE {
  REFERENCE_NM varchar(100) [not null]
  VERSION_ID nvarchar [not null]
  CELL_TYPE_CD varchar(10)
  PROCESS_SQN nvarchar
  ORDER_SQN nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table QUOTES_OUTPUT_CASE_DATA {
  CASE_DATA_ID nvarchar [not null]
  CASE_ID nvarchar [not null]
  VERSION_ID nvarchar
  REFERENCE_NM varchar(250)
  CONTENT_TX varchar(4000)
  CREATE_USER_ID varchar(50)
  CREATE_TS nvarchar
  UPDATE_USER_ID varchar(50)
  UPDATE_TS nvarchar
}

Table QUOTES_OUTPUT_CELL_REFERENCE {
  REFERENCE_NM varchar(100) [not null]
  VERSION_ID nvarchar [not null]
  CELL_TYPE_CD varchar(10)
  PROCESS_SQN nvarchar
  ORDER_SQN nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table QUOTES_TASK_DATA {
  TASK_DATA_ID nvarchar [not null]
  TASK_LU_ID nvarchar
  PROJECT_DATA_ID nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table QUOTES_TASK_ROLE {
  TASK_ROLE_ID nvarchar [not null]
  TASK_LU_ID nvarchar [not null]
  ROLE_ID nvarchar [not null]
  CREATE_USER_ID varchar(50) [not null]
  CREATE_TS datetime2
  UPDATE_USER_ID nvarchar(100)
  UPDATE_TS datetime2
}

Table QUOTES_TASKS {
  TASK_ID nvarchar [not null]
  TASK_LU_ID nvarchar [not null]
  STATUS_ID nvarchar [not null]
  ASSIGNED_USER_ID nvarchar
  START_DATE nvarchar
  END_DATE nvarchar
  APPROVAL1 nvarchar [not null]
  APPROVAL2 nvarchar [not null]
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  TOOL_TASK_ID nvarchar
  QUOTE_ID nvarchar
  IS_ESCALATED nvarchar [not null]
}

Table QUOTES_UPDATED {
  QUOTE_ID numeric(10)
  QUOTE_NUMBER nvarchar(60)
  DESCRIPTION nvarchar(240)
  ACCOUNT_ID numeric(10)
  SOLUTION_TYPE_ID numeric(10)
  REVISION numeric(10)
  DATE_OF_INQUIRY datetime
  IMPORT_TYPE numeric(10)
  PAYMENTS_TYPES numeric(10)
  CREATE_USER_ID nvarchar(100)
  CREATE_TS datetime2
  UPDATE_USER_ID nvarchar(100)
  UPDATE_TS datetime2
  CUSTOMER_NEED_DATE datetime
  ESTIMATED_LEAD_TIME nvarchar(120)
  QUOTES_STATUS numeric(10)
  QUOTE_TEMPLATE nvarchar(120)
  CUSTOMER_ADDRESS nvarchar(76)
  REGION_ID nvarchar(76)
  CUSTOMER_CONTACT nvarchar(120)
  SHIP_TO nvarchar(240)
  CUSTOMER_RFQ nvarchar(240)
  QUOTE_PART_NUMBER nvarchar(120)
  INCOTERMS_ID nvarchar(76)
  TERADYNE_ADDRESS nvarchar(1000)
  TERADYNE_ENTITY_CONTACT nvarchar(76)
  SALES_PERSON nvarchar(240)
  DIS_MASTER_KEY nvarchar(40)
  SHARED_SOLUTION_DATA_ID nvarchar(76)
  QUOTE_ID_dst numeric(10)
}

Table REGIONS {
  REGION_ID nvarchar [pk, not null]
  REGION_NM varchar(50)
  REGION_DS varchar(250)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  ACTIVE nvarchar [not null]
}

Table RESPONSE_LU {
  RESPONSE_LU_ID nvarchar [pk, not null]
  RESPONSE_DS nvarchar(300)
  APPROVAL_LEVEL_ID nvarchar
  CREATE_USER_ID nvarchar(100)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table ROLE {
  ROLE_ID nvarchar [pk, not null]
  ROLE_NM varchar(50)
  ROLE_DS varchar(250)
  CREATE_PROJ_FL nvarchar
  EDIT_PROJECT_FL nvarchar
  EDIT_ASSIGNMENTS_FL nvarchar
  COMPLETE_TASKS_FL nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  REVIEW_DESIGN_FL nvarchar
  PROJ_ACCESS_FL nvarchar
}

Table SCHEDULE {
  SCHEDULE_ID nvarchar [pk, not null]
  SOW_CASE_ID nvarchar [not null]
  MILESTONE varchar(200)
  DESIGN_START_DATE datetime2
  DESIGN_FINISH_DATE datetime2
  OWNER nvarchar
  CREATE_TS datetime2
  CREATE_USER_ID varchar(20)
  UPDATE_USER_ID varchar(20)
  UPDATE_TS datetime2
}

Table SOLUTION_TYPE {
  SOLUTION_TYPE_ID nvarchar [pk]
  SOLUTION_TYPE_NAME varchar(25)
  CREATE_USER_ID varchar(250)
  CREATE_TS datetime2
  UPDATE_USER_IS varchar(50)
  UPDATE_TS datetime2
  TOOL_ID nvarchar
}

Table SOW {
  SOW_ID nvarchar [pk, not null]
  STATUS nvarchar [not null]
  DESCRIPTION varchar(200)
  ASSIGNED_ID nvarchar
  START_DATE datetime2
  END_DATE datetime2
  CREATE_TS datetime2
  CREATE_USER_ID varchar(20)
  UPDATE_USER_ID varchar(20)
  UPDATE_TS datetime2
  DIS_MASTER_KEY varchar(20)
  SHARED_SOLUTION_DATA_ID nvarchar
}

Table SOW_APPROVALS {
  SOW_APPROVALS_ID nvarchar [pk, not null]
  SOW_CASES_ID nvarchar [not null]
  APPROVALS_ID nvarchar [not null]
  CREATE_TS datetime2
  CREATE_USER_ID varchar(20)
  UPDATE_USER_ID varchar(20)
  UPDATE_TS datetime2
}

Table SOW_CASE_FILES {
  SOW_CASE_FILES_ID nvarchar [pk, not null]
  SOW_CASE_ID nvarchar [not null]
  FILE_ID nvarchar [not null]
  CREATE_TS datetime2
  CREATE_USER_ID varchar(20)
  UPDATE_USER_ID varchar(20)
  UPDATE_TS datetime2
  FILE_SENT char(1)
}

Table SOW_CASES {
  SOW_CASE_ID nvarchar [not null]
  SOW_VERSION_ID varchar(20)
  SOW_ID nvarchar
  STATUS varchar(20)
  PROJECT_OBJECTIVE varchar(100)
  CUSTOMER_REQUIREMENTS varchar(100)
  CUSTOMER_ACCEPTANCE_CRITERIA varchar(100)
  PROJECT_DELIVERABLES varchar(100)
  PROJECT_LEAD_ID nvarchar
  TECHNICAL_LEAD_ID nvarchar
  CHINA_DESIGN_LEAD_ID nvarchar
  PLANNER_ID nvarchar
  SUPPLIER_QUIALITY_ENGINEER nvarchar
  CREATE_TS datetime2
  CREATE_USER_ID varchar(20)
  UPDATE_USER_ID varchar(20)
  FIRST_SAVED_FLAG nvarchar
  UPDATE_TS datetime2
  CHDC_MANAGER_ID nvarchar
}

Table STAGES {
  STAGE_ID nvarchar [not null]
  STAGE_NM varchar(50)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table STATUS {
  STATUS_ID nvarchar [pk, not null]
  SEQ_NO nvarchar
  STATUS_DS varchar(50) [not null]
  APPROVAL_ID nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table SUB_PROJECT_TYPE {
  SUB_PROJECT_TYPE_ID nvarchar [pk]
  SUB_PROJECT_TYPE_NM varchar(25)
  SUB_PROJECT_TYPE_DS varchar(250)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table SUB_PROJECTS {
  SUBPROJ_ID nvarchar [not null]
  PROJECT_ID nvarchar
  SUBPROJ_NM varchar(50)
  SUBPROJ_DS varchar(250)
  STAGE_ID nvarchar
  TER_PN varchar(50)
  PROJECT_LEAD_ID nvarchar
  DESIGN_LEAD_ID nvarchar
  REGION_ID nvarchar
  CUSTOMER varchar(50)
  CUSTOMER_BUYER_ID nvarchar
  CUSTOMER_SPECIFIER_ID nvarchar
  PLANNER_ID nvarchar
  SQE_ID nvarchar
  PROJECT_AWARD_DT datetime2
  KICKOFF_DT datetime2
  DELIVERY_DT datetime2
  PLATFORM_DS varchar(50)
  APPLICATION_DS varchar(50)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  SUB_PROJECT_TYPE_ID nvarchar
  SUP_NAME varchar(200)
  SHARED_ID varchar(50)
  SHARED_SOLUTION_DATA_ID nvarchar
}

Table SUPPLIER_ROLE {
  SUPPLIER_ROLE_ID nvarchar [pk, not null]
  SUPPLIER_TYPE_ID nvarchar [not null]
  SUPPLIER_ID nvarchar
}

Table SUPPLIER_TYPES {
  SUPPLIER_TYPE_ID nvarchar [not null]
  SUPPLIER_NAME varchar(100) [not null]
}

Table SUPPLIERS {
  SUPPLIER_ID nvarchar [pk, not null]
  SUPPLIER_NAME varchar(100) [not null]
  SUPPLIER_TYPE_ID nvarchar
}

Table SUPPLY_CHAIN {
  SUPPLY_CHAIN_ID nvarchar [pk, not null]
  SUPPLIER_PCB_FABRICATION_ID nvarchar
  SUPPLIER_PCB_ASSEMBLY_ID nvarchar
  MLO_FABRICATION_ID nvarchar
  MLO_ASSEMBLY_AND_ATTACH_ID nvarchar
  FLYING_PROBE_TEST_ID nvarchar
  PROBE_HEAD_SOCKET_VENDOR_ID nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table SUPPLY_CHAIN_COMPONENTS {
  SUPPLY_CHAIN_ID nvarchar [not null]
  SUPPLIER_ROLE_ID nvarchar [not null]
  IS_MAIN_COMPONENT_SUPP char(1) [not null]
}

Table SUPPLY_CHAIN_PATH {
  SC_PATH_ID nvarchar [not null]
  FAB_COMPLEXITY nvarchar
  REGION_ID nvarchar
  HW_TYPE_ID nvarchar
  FAB_SUPPLIER_ID nvarchar
  ASSY_SUPPLIER_ID nvarchar
  FPT_SUPPLIER_ID nvarchar
}

Table sysdiagrams {
  name sysname [not null]
  principal_id int [not null]
  diagram_id int [not null]
  version int
  definition varbinary
}

Table TASK_DATA {
  TASK_DATA_ID nvarchar [pk, not null]
  TASK_LU_ID nvarchar
  PROJECT_DATA_ID nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table TASK_ROLE {
  TASK_ROLE_ID nvarchar [pk, not null]
  TASK_LU_ID nvarchar [not null]
  ROLE_ID nvarchar [not null]
  CREATE_USER_ID varchar(50) [not null]
  CREATE_TS datetime2
  UPDATE_USER_ID nvarchar(100)
  UPDATE_TS datetime2
}

Table TASKS {
  TASK_ID nvarchar [pk, not null]
  TASK_LU_ID nvarchar [not null]
  STATUS_ID nvarchar [not null]
  ASSIGNED_USER_ID nvarchar
  START_DATE nvarchar
  END_DATE nvarchar
  SUBPROJ_ID nvarchar
  APPROVAL1 nvarchar [not null]
  APPROVAL2 nvarchar [not null]
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  PROJECT_ID nvarchar
  TOOL_TASK_ID nvarchar
  ACTUAL_START_DATE nvarchar
  ACTUAL_END_DATE nvarchar
  SHARED_SOLUTION_DATA_ID nvarchar
}

Table TASKS_LU {
  TASK_LU_ID nvarchar [not null]
  PROJECT_TYPE_ID nvarchar
  SEQ_NO nvarchar [not null]
  PHASE varchar(50)
  TASK_NM varchar(100) [not null]
  TASK_DS varchar(250)
  APPROVAL_ID nvarchar
  TOOL_ID nvarchar
  FILE_FL nvarchar [not null]
  TASK_FILES_ID nvarchar [not null]
  SCREEN_ID nvarchar [not null]
  TRIGGER_TASK_ID nvarchar [not null]
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  SUB_PROJECT_TYPE_ID nvarchar
  TOOL_MODE_ID nvarchar
  STATUS_LIST_ID nvarchar
}

Table TER_ADDRESSES {
  ID nvarchar [pk, not null]
  ADDRESSES varchar(500) [not null]
  REGION_ID nvarchar [not null]
}

Table TER_ENTITIES {
  ID nvarchar [pk]
  NAME varchar(60)
  DESCRIPTION varchar(60)
  ID_REGION nvarchar
}

Table TEST_PLATFORMS {
  ID nvarchar [pk, not null]
  TEST_PLATFORM_NM varchar(150) [not null]
}

Table TOFU_QUOTE {
  TOFU_QUOTE_ID nvarchar [pk, not null]
  SALES_REQUESTED_DISCOUNT float
  SALES_PRICER_PER_UNIT float
  SALES_REQUESTED_NRE_DISCOUNT float
  SALES_REQUESTED_PRICE_NRE float
  SALES_REQUESTED_PRICE_PCB float
  SALES_COMMENT varchar(500)
  REGIONAL_MANAGER_DISCOUNT float
  REGIONAL_MANAGER_PRICER_PER_UNIT float
  REGIONAL_MANAGER_NRE_DISCOUNT float
  REGIONAL_MANAGER_FINAL_PRICE_PCB float
  REGIONAL_MANAGER_FINAL_PRICE_NRE float
  REGIONAL_MANAGER_COMMENT varchar(500)
  FIRST_GLOBAL_MANAGER_DISCOUNT float
  FIRST_GLOBAL_MANAGER_PRICER_PER_UNIT float
  FIRST_GLOBAL_MANAGER_NRE_DISCOUNT float
  FIRST_GLOBAL_MANAGER_FINAL_PRICE_PCB float
  FIRST_GLOBAL_MANAGER_FINAL_PRICE_NRE float
  FIRST_GLOBAL_MANAGER_COMMENT varchar(500)
  SECOND_GLOBAL_MANAGER_DISCOUNT float
  SECOND_GLOBAL_MANAGER_PRICER_PER_UNIT float
  SECOND_GLOBAL_MANAGER_NRE_DISCOUNT float
  SECOND_GLOBAL_MANAGER_FINAL_PRICE_PCB float
  SECOND_GLOBAL_MANAGER_FINAL_PRICE_NRE float
  SECOND_GLOBAL_MANAGER_COMMENT varchar(500)
  STATUS varchar(50)
  CREATED_BY varchar(20)
  CREATED_DATE nvarchar
  UPDATED_DATE nvarchar
  QUOTE_ID nvarchar
  CASE_ID nvarchar
  RETRACTED char(1)
  FINAL_PRICE_PCB float
  FINAL_PRICE_NRE float
  PCB_DISCOUNT float
  NRE_DISCOUNT float
}

Table TOOL_VERSION {
  TOOL_VERSION_ID nvarchar [pk, not null]
  TOOL_ID nvarchar
  VERSION_NO varchar(50) [not null]
  VERSION_DS varchar(50) [not null]
  EASA_DIR varchar(50) [not null]
  EXCEL_TOOL_VER varchar(50)
  CREATED_DT nvarchar [not null]
  EFFECTIVE_DT nvarchar
  EXPIRATION_DT nvarchar
  CREATE_USER_ID varchar(50) [not null]
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table TOOLS {
  TOOL_ID nvarchar [pk, not null]
  TOOL_DS varchar(250) [not null]
  DATA_ITEM1_NM varchar(250)
  DATA_ITEM2_NM varchar(250)
  DATA_ITEM3_NM varchar(250)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  DATA_ITEM4_NM varchar(250)
}

Table USER_ROLE {
  USER_ROLE_ID nvarchar [pk, not null]
  USER_ID nvarchar
  ROLE_ID nvarchar
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table USER_WORKGROUP {
  USER_ID nvarchar [not null]
  WORKGROUP_ID nvarchar
  ACCESS_LEVEL_CD varchar(10)
  ACTIVE_IN char(1)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table USERS {
  USER_ID int [pk, not null]
  FIRST_NM varchar(25)
  LAST_NM varchar(25)
  ROLE_ID nvarchar
  LOGIN_ID varchar(50)
  REGION_ID nvarchar [not null]
  ACTIVE_IN char(1)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  ACCOUNT_ID nvarchar
  WORKGROUP_ID nvarchar
  EMAIL varchar(60)
}

Table WORKGROUP {
  WORKGROUP_ID nvarchar [pk, not null]
  WORKGROUP_NM varchar(25)
  WORKGROUP_DS varchar(50)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
}

Table YMS_CELL_REFERENCE {
  REFERENCE_NM varchar(100) [not null]
  VERSION_ID nvarchar [not null]
  CELL_TYPE_CD varchar(20)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
}

Table YMS_DATA {
  YMS_DATA_ID nvarchar [pk, not null]
  VERSION_ID nvarchar [not null]
  REFERENCE_NM varchar(250)
  CONTENT_TX varchar(4000)
  CREATE_USER_ID varchar(50)
  CREATE_TS datetime2
  UPDATE_USER_ID varchar(50)
  UPDATE_TS datetime2
  CASE_ID nvarchar
}

Ref: APPROVAL_ESCALATIONS_LU.USER_ID > USERS.USER_ID
Ref: APPROVALS.TASK_ID > TASKS.TASK_ID
Ref: APPROVALS_LU.PROJECT_DATA_ID > PROJECT_DATA.PROJECT_DATA_ID
Ref: APPROVALS_LU.TOOL_ID > TOOLS.TOOL_ID
Ref: CASES.TASK_ID > TASKS.TASK_ID
Ref: CASES.TOOL_VERSION_ID > TOOL_VERSION.TOOL_VERSION_ID
Ref: CASES.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: COPY_PRICER_MODEL.TASK_ID > TASKS.TASK_ID
Ref: COPY_PRICER_MODEL.USER_ID > USERS.USER_ID
Ref: CUSTOMER_ADD_UPDATED.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: CUSTOMER_ADDRESS.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: DESIGN_COMPLEXITY.TASK_ID > TASKS.TASK_ID
Ref: DESIGN_COMPLEXITY.TOOL_VERSION_ID > TOOL_VERSION.TOOL_VERSION_ID
Ref: DIS_MASTER_TABLE.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: DIS_MASTER_TABLE.REGION_ID > REGIONS.REGION_ID
Ref: FILES.PROJECT_ID > PROJECTS.PROJECT_ID
Ref: FILES.TASK_ID > TASKS.TASK_ID
Ref: FINAL_REVIEW.HLA_ID > HLA.HLA_ID
Ref: HLA.PROJECT_ID > PROJECTS.PROJECT_ID
Ref: HLA.SOW_ID > SOW.SOW_ID
Ref: ISSUES.PROJECT_ID > PROJECTS.PROJECT_ID
Ref: ISSUES.TASK_ID > TASKS.TASK_ID
Ref: LOG.TOOL_ID > TOOLS.TOOL_ID
Ref: LOG.SOW_ID > SOW.SOW_ID
Ref: OPP_MG_CUSTOMER_PROJECTS.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: OPP_MG_CUSTOMER_PROJECTS.CUSTOMER_CATEGORY_ID > CUSTOMER_CATEGORY.CUSTOMER_CATEGORY_ID
Ref: OPP_MG_NPI_REPEAT.PROJECT_TYPE_ID > PROJECT_TYPE.PROJECT_TYPE_ID
Ref: OPP_MG_NPI_REPEAT.SUPPLY_CHAIN_ID > SUPPLY_CHAIN.SUPPLY_CHAIN_ID
Ref: OPP_MG_NPI_REPEAT_DATE_CHANGE_APPROVALS.APPROVALS_ID > APPROVALS.APPROVAL_ID
Ref: PROJECT_DATA_REFERENCE.PROJECT_DATA_ID > PROJECT_DATA.PROJECT_DATA_ID
Ref: PROJECT_TYPE.TOOL_ID > TOOLS.TOOL_ID
Ref: PROJECTS.PROJECT_TYPE_ID > PROJECT_TYPE.PROJECT_TYPE_ID
Ref: PROJECTS.REGION_ID > REGIONS.REGION_ID
Ref: PROJECTS.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: QUOTE_STATUS.STATUS_ID > STATUS.STATUS_ID
Ref: QUOTE_STATUS.APPROVAL_ID > APPROVALS.APPROVAL_ID
Ref: QUOTES.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: QUOTES.SOLUTION_TYPE_ID > SOLUTION_TYPE.SOLUTION_TYPE_ID
Ref: QUOTES.REGION_ID > REGIONS.REGION_ID
Ref: QUOTES.INCOTERMS_ID > INCOTERMS.ID
Ref: QUOTES_CASE_DATA.CASE_DATA_ID > CASE_DATA.CASE_DATA_ID
Ref: QUOTES_CASES.TASK_ID > TASKS.TASK_ID
Ref: QUOTES_CASES.TOOL_VERSION_ID > TOOL_VERSION.TOOL_VERSION_ID
Ref: QUOTES_CASES.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: QUOTES_CASES_UPDATED.TASK_ID > TASKS.TASK_ID
Ref: QUOTES_CASES_UPDATED.TOOL_VERSION_ID > TOOL_VERSION.TOOL_VERSION_ID
Ref: QUOTES_CASES_UPDATED.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: QUOTES_OUTPUT_CASE_DATA.CASE_DATA_ID > CASE_DATA.CASE_DATA_ID
Ref: QUOTES_TASK_DATA.TASK_DATA_ID > TASK_DATA.TASK_DATA_ID
Ref: QUOTES_TASK_DATA.PROJECT_DATA_ID > PROJECT_DATA.PROJECT_DATA_ID
Ref: QUOTES_TASK_ROLE.TASK_ROLE_ID > TASK_ROLE.TASK_ROLE_ID
Ref: QUOTES_TASK_ROLE.ROLE_ID > ROLE.ROLE_ID
Ref: QUOTES_TASKS.TASK_ID > TASKS.TASK_ID
Ref: QUOTES_TASKS.STATUS_ID > STATUS.STATUS_ID
Ref: QUOTES_UPDATED.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: QUOTES_UPDATED.SOLUTION_TYPE_ID > SOLUTION_TYPE.SOLUTION_TYPE_ID
Ref: QUOTES_UPDATED.REGION_ID > REGIONS.REGION_ID
Ref: QUOTES_UPDATED.INCOTERMS_ID > INCOTERMS.ID
Ref: SOLUTION_TYPE.TOOL_ID > TOOLS.TOOL_ID
Ref: SOW_APPROVALS.APPROVALS_ID > APPROVALS.APPROVAL_ID
Ref: SOW_CASES.SOW_ID > SOW.SOW_ID
Ref: STATUS.APPROVAL_ID > APPROVALS.APPROVAL_ID
Ref: SUB_PROJECTS.PROJECT_ID > PROJECTS.PROJECT_ID
Ref: SUB_PROJECTS.REGION_ID > REGIONS.REGION_ID
Ref: SUB_PROJECTS.SUB_PROJECT_TYPE_ID > SUB_PROJECT_TYPE.SUB_PROJECT_TYPE_ID
Ref: SUPPLIER_ROLE.SUPPLIER_ID > SUPPLIERS.SUPPLIER_ID
Ref: SUPPLY_CHAIN_COMPONENTS.SUPPLY_CHAIN_ID > SUPPLY_CHAIN.SUPPLY_CHAIN_ID
Ref: SUPPLY_CHAIN_COMPONENTS.SUPPLIER_ROLE_ID > SUPPLIER_ROLE.SUPPLIER_ROLE_ID
Ref: SUPPLY_CHAIN_PATH.REGION_ID > REGIONS.REGION_ID
Ref: TASK_DATA.PROJECT_DATA_ID > PROJECT_DATA.PROJECT_DATA_ID
Ref: TASK_ROLE.ROLE_ID > ROLE.ROLE_ID
Ref: TASKS.STATUS_ID > STATUS.STATUS_ID
Ref: TASKS.PROJECT_ID > PROJECTS.PROJECT_ID
Ref: TASKS_LU.PROJECT_TYPE_ID > PROJECT_TYPE.PROJECT_TYPE_ID
Ref: TASKS_LU.APPROVAL_ID > APPROVALS.APPROVAL_ID
Ref: TASKS_LU.TOOL_ID > TOOLS.TOOL_ID
Ref: TASKS_LU.SUB_PROJECT_TYPE_ID > SUB_PROJECT_TYPE.SUB_PROJECT_TYPE_ID
Ref: TER_ADDRESSES.REGION_ID > REGIONS.REGION_ID
Ref: TOOL_VERSION.TOOL_ID > TOOLS.TOOL_ID
Ref: USER_ROLE.USER_ID > USERS.USER_ID
Ref: USER_ROLE.ROLE_ID > ROLE.ROLE_ID
Ref: USER_WORKGROUP.USER_ID > USERS.USER_ID
Ref: USER_WORKGROUP.WORKGROUP_ID > WORKGROUP.WORKGROUP_ID
Ref: USERS.ROLE_ID > ROLE.ROLE_ID
Ref: USERS.REGION_ID > REGIONS.REGION_ID
Ref: USERS.ACCOUNT_ID > ACCOUNTS.ACCOUNT_ID
Ref: USERS.WORKGROUP_ID > WORKGROUP.WORKGROUP_ID
